server:
  port: 8080

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@  # 当前激活配置，默认dev
  messages:
    # basename 中的 . 和 / 都可以用来表示文件层级，默认的 basename 是 messages
    # 必须注册此 basename, 否则 security 错误信息将一直都是英文
    basename: 'org.springframework.security.messages'

# 图形验证码
aj:
  captcha:
    water-mark: 'BallCat'
    cache-type: redis

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


# BallCat 相关配置
ballcat:
  security:
    # 前端传输密码的 AES 加密密钥
    password-secret-key: '==BallCat-Auth=='
    oauth2:
      authorizationserver:
        # 登陆验证码是否开启
        login-captcha-enabled: true
      resourceserver:
        ## 忽略鉴权的 url 列表
        ignore-urls:
          - /public/**
          - /actuator/**
          - /doc.html
          - /v2/api-docs/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
          - /webjars/**
          - /bycdao-ui/**
          - /favicon.ico
          - /captcha/**
  # 项目 redis 缓存的 key 前缀
  redis:
    key-prefix: 'ballcat:'
  # actuator 加解密密钥
  actuator:
    auth: true
    secret-id: 'ballcat-monitor'
    secret-key: '=BallCat-Monitor'
  openapi:
    info:
      title: BallCat-Admin Docs
      description: BallCat 后台管理服务Api文档
      version: ${project.version}
      terms-of-service: http://www.ballcat.cn/
      license:
        name: Powered By BallCat
        url: http://www.ballcat.cn/
      contact:
        name: Hccake
        email: chengbohua@foxmail.com
        url: https://github.com/Hccake
    components:
      security-schemes:
        apiKey:
          type: APIKEY
          in: HEADER
          name: 'api-key'
        oauth2:
          type: OAUTH2
          flows:
            password:
              token-url: /oauth/token
    security:
      - oauth2: []
      - apiKey: []

springdoc:
  swagger-ui:
    oauth:
      client-id: test
      client-secret: test
    display-request-duration: true
    disable-swagger-default-url: true
    persist-authorization: true







